// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_prZM2p7_tCh_n-8NU7-g_TDT2UYI3Hg',
    appId: '1:761647282034:android:7ae7a71e22c72029998feb',
    messagingSenderId: '761647282034',
    projectId: 'weeeeeeek5',
    storageBucket: 'weeeeeeek5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9sB89FkBfkhB5lZbdVm0pfErVEtR7RQo',
    appId: '1:761647282034:ios:bc871714f5f92cab998feb',
    messagingSenderId: '761647282034',
    projectId: 'weeeeeeek5',
    storageBucket: 'weeeeeeek5.firebasestorage.app',
    iosBundleId: 'com.example.week5auth.week5Auth',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKyZUC0kv68ezt4spacjhaa9Yun7Z-wrI',
    appId: '1:761647282034:web:40adfbb69a6fd52b998feb',
    messagingSenderId: '761647282034',
    projectId: 'weeeeeeek5',
    authDomain: 'weeeeeeek5.firebaseapp.com',
    storageBucket: 'weeeeeeek5.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9sB89FkBfkhB5lZbdVm0pfErVEtR7RQo',
    appId: '1:761647282034:ios:bc871714f5f92cab998feb',
    messagingSenderId: '761647282034',
    projectId: 'weeeeeeek5',
    storageBucket: 'weeeeeeek5.firebasestorage.app',
    iosBundleId: 'com.example.week5auth.week5Auth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKyZUC0kv68ezt4spacjhaa9Yun7Z-wrI',
    appId: '1:761647282034:web:5c0b5f253cc8f8a4998feb',
    messagingSenderId: '761647282034',
    projectId: 'weeeeeeek5',
    authDomain: 'weeeeeeek5.firebaseapp.com',
    storageBucket: 'weeeeeeek5.firebasestorage.app',
  );

}